name: Deploy app
on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - name: NPM CI
        run: npm ci

      - name: Testing Rsync
        run: rsync -avzr --delete --rsh="/usr/bin/sshpass -p ${{ secrets.SSH_REMOTE_PASS }} ssh -o StrictHostKeyChecking=no -o PubkeyAuthentication=no -o PreferredAuthentications=password -l ${{ secrets.SSH_REMOTE_USER }}" . ${{ secrets.SSH_REMOTE_USER }}@${{ secrets.SSH_REMOTE_HOST }}:${{ vars.SSH_REMOTE_RSYNC_PATH }}

      - name: Pm2 Reload
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_REMOTE_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/syedusmanabid627/hello-world
            #export PATH=/root/.nvm/versions/node/v18.17.1/bin:/usr/bin
            export GIT_REVISION=$(git rev-parse HEAD)
            pm2 reload app.js --name app --update-env
